### ISSUE TITLE
希望能增加更新内核功能

### ISSUE THREAD

**Issue by smdx** [kiddin9/openwrt-bypass#63]
希望能增加更新内核功能不然内核更新了得等版本更新，增加内核更新功能就方便多了。谢谢

**Comment by kiddin9** [comment]
内核指的是? xray-core? xray-core不是可以在线更新么,

**Comment by smdx** [comment]
> 内核指的是? xray-core? xray-core不是可以在线更新么,

是xray-core，在bypass界面没看到更新选项啊.......请问在哪个菜单？谢谢

路由固件：OpenWrt JZ 2021.09.21 by Sirpdboy
bypass版本：luci-app-bypass 1.2-77

**Comment by kiddin9** [comment]
![image](https://user-images.githubusercontent.com/48883331/134342709-5f65cad6-64ee-4967-8046-cb5fef3245fe.png)
默认是有这个功能的,可能是你固件作者把这个功能去掉了,

**Comment by smdx** [comment]
哎，谢谢。那我向固件作者反馈一下。麻烦你了。

**Comment by kiddin9** [comment]
固件作者可能是故意去掉的,更新需要在这里https://github.com/XTLS/Xray-core/releases下载cpu对应的xray-core,这里应该没有N1对应的xray可供下载,

**Comment by smdx** [comment]
好的，谢谢
