### ISSUE TITLE
插件自动配置dnsmasq禁止解析 IPv6 DNS 记录

### ISSUE THREAD

**Issue by quanjindeng** [kiddin9/openwrt-bypass#75]
重启后，插件自动配置dnsmasq禁止解析 IPv6 DNS 记录，不知道这是不是刻意这么设置的，但应该也有不少人跟我一样需要ipv6。
每次重启后都需要手动打开ipv6解析还是挺麻烦的，而且打开后好像也没影响代理，希望作者大佬可以修复下（或者提供个选择是否禁用ipv6解析）。

**Comment by kiddin9** [comment]
不存在的,只会默认屏蔽国外网站的ipv6,不影响国内,因为国外网站都走的代理,大部分代理都不支持ipv6

**Comment by quanjindeng** [comment]
感谢回复，因为重新应用bypass插件时发现改变了DNS缓存大小，所以第一时间怀疑是这个插件。
现在把跟DNS有关的其他插件卸载了，重启几次都没发现这个问题了
